# Generated by Django 3.0.9 on 2020-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_choice',
            field=models.CharField(choices=[('allow-comment', 'allow-comment'), ('not-allow-comment', 'not-allow-comment')], default='allow-comment', max_length=17),
        ),
    ]
