# Generated by Django 3.0.9 on 2020-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_comment_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(blank=True, choices=[('public', 'public'), ('friends', 'friends')], default='public', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_choice',
            field=models.CharField(blank=True, choices=[('allow-comment', 'allow-comment'), ('not-allow-comment', 'not-allow-comment')], default='allow-comment', max_length=17),
        ),
    ]
