# Generated by Django 3.0.9 on 2020-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200903_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_choice',
            field=models.CharField(choices=[('allow-comment', 'allow-comment'), ('not-allow-comment', 'not-allow-comment')], default='allow-comment', max_length=17),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('friends', 'friends')], default='public', max_length=7),
        ),
    ]
