# Generated by Django 3.0.9 on 2020-09-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_relation'),
        ('posts', '0004_auto_20200903_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('not_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_receiver', to='profiles.Profile')),
                ('not_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_sender', to='profiles.Profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
