# Generated by Django 3.0.9 on 2020-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('liked', 'liked'), ('commented', 'commented'), ('friend', 'friend')], default='liked', max_length=9),
        ),
    ]
