# Generated by Django 3.0.9 on 2020-09-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200905_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('liked', 'liked'), ('commented', 'commented'), ('friend', 'friend'), ('accept', 'accept')], default='liked', max_length=9),
        ),
    ]
