# Generated by Django 3.0.9 on 2020-09-07 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200906_2358'),
        ('posts', '0010_auto_20200905_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall', to='profiles.Profile'),
        ),
    ]
