# Generated by Django 3.0.9 on 2020-09-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200906_2358'),
        ('posts', '0013_auto_20200908_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Profile'),
        ),
    ]
