# Generated by Django 3.0.9 on 2020-09-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200904_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='block',
            field=models.CharField(choices=[('block', 'block'), ('unblock', 'unblock')], default='unblock', max_length=7, null=True),
        ),
    ]
